OOP_Community/Controllers/MonthlyDuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OOP_Community.Models;

namespace OOP_Community.Controllers
{
    public class MonthlyDuesController : DBController
    {
        // GET: MonthlyDue
        public ActionResult CreateMonthlyDues()
        {
            if (Session["idUser"] == null)
            {
                return RedirectToAction("../Home/Login");
            }

            MyCommunity_DBEntities db = getDB();

            try
            {
                var residentList = (from resident in db.Residents
                                    select resident).ToList();
                ViewData["residents"] = residentList;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return View();
        }
        public ActionResult ManageMonthlyDues()
        {
            if (Session["idUser"] == null)
            {
                return RedirectToAction("../Home/Login");
            }
            MyCommunity_DBEntities db = getDB();
            List<Resident> residentList = db.Residents.ToList();
            List<User> userList = db.Users.ToList();
            List<Transaction> transactionList = db.Transactions.ToList();
            List<Monthly_Due> monthlyDueList = db.Monthly_Due.ToList();
            try
            {
                ViewData["monthlyDues"] = (from transaction in transactionList
                                           join user in userList on transaction.transactedBy equals user.id into ul
                                           from subuser in ul.DefaultIfEmpty()

                                           join monthlydue in monthlyDueList on transaction.monthly_Due equals monthlydue.id into mdl
                                           from submonthlydue in mdl.DefaultIfEmpty()

                                           join resident in residentList on transaction.resident equals resident.id into rl
                                           from subresident in rl.DefaultIfEmpty()

                                           select new MonthlyDuesJoin
                                           {
                                               TransactionList = transaction,
                                               UserList = subuser,
                                               MonthlyDueList = submonthlydue,
                                               ResidentList = subresident
                                           }).ToList();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return View();
        }
        public ActionResult CreatingMonthlyDues(FormCollection fc)
        {
            MyCommunity_DBEntities db = getDB();
            Monthly_Due m = new Monthly_Due();
            try
            {
                var residentList = (from resident in db.Residents
                                    select resident).ToList();

                m.monthlyFee = Convert.ToDecimal(fc["monthlyFee"]);
                m.month = fc["month"];
                m.dueDate = Convert.ToDateTime(fc["dueDate"]);
                m.createdBy = Convert.ToInt16(Session["idUser"]);
                db.Monthly_Due.Add(m);
                int monthly_Due = m.id;

                foreach (var resident in residentList)
                {
                    Transaction t = new Transaction();
                    t.monthly_Due = monthly_Due;
                    t.resident = resident.id;
                    t.paidStatus = false;
                    db.Transactions.Add(t);
                }
                int res = db.SaveChanges();
                if (res > 0)
                    Session["Message"] = "Monthly Dues has been created successfully.";
                else
                    Session["Message"] = "Failed to create monthly dues, please try again.";
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return RedirectToAction("CreateMonthlyDues");
        }
        public ActionResult UpdateMonthlyDues(FormCollection fc)
        {
            MyCommunity_DBEntities db = getDB();

            try
            {
                int transactionID = Convert.ToInt16(fc["transactionID"]);

                var transactions = (from transaction in db.Transactions
                                    where transaction.id == transactionID
                                    select transaction);

                foreach (Transaction transaction in transactions)
                {
                    transaction.transactedBy = Convert.ToInt16(Session["idUser"]);
                    transaction.paidStatus = Convert.ToBoolean(fc["paidStatus"]);
                    if (fc["paidDate"] != " " || fc["paidDate"] != "" || fc["paidDate"] != null)
                        transaction.paidDate = Convert.ToDateTime(fc["paidDate"]);
                }

                int res = db.SaveChanges();
                if (res > 0)
                    Session["Message"] = "A transaction has been updated successfully.";
                else
                    Session["Message"] = "Failed to update transaction, please try again.";
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return RedirectToAction("ManageMonthlyDues");
        }
        public ActionResult DeleteTransactions()
        {
            MyCommunity_DBEntities db = getDB();
            try
            {
                int transactionID = Convert.ToInt16(Request["transactionID"]);
                var deleteTransaction = (from transaction in db.Transactions
                                         where transaction.id == transactionID
                                         select transaction).FirstOrDefault();
                db.Transactions.Remove(deleteTransaction);

                int res = db.SaveChanges();
                if (res > 0)
                    Session["Message"] = "A transaction has been deleted successfully.";
                else
                    Session["Message"] = "Failed to delete transaction, please try again.";
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return RedirectToAction("ManageMonthlyDues");
        }
    }
}

OOP_Community/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OOP_Community.Models;

namespace OOP_Community.Controllers
{
    public class ProjectController : DBController
    {
        public ActionResult CreateProject()
        {
            if (Session["idUser"] == null)
            {
                return RedirectToAction("../Home/Login");
            }

            return View();
        }
        public ActionResult AddingProjects(FormCollection fc)
        {
            MyCommunity_DBEntities db = getDB();
            Project p = new Project();

            try
            {
                p.name = fc["name"];
                p.description = fc["description"];
                p.cost = Convert.ToDecimal(fc["cost"]);
                p.status = fc["status"];
                p.dateStarted = Convert.ToDateTime(fc["dateStarted"]);
                p.dateFinished = Convert.ToDateTime(fc["dateFinished"]);
                p.issuedBy = Convert.ToInt16(Session["idUser"]);
                db.Projects.Add(p);

                int res = db.SaveChanges();
                if (res > 0)
                    Session["Message"] = "A project has been created successfully.";
                else
                    Session["Message"] = "Failed to create project, please try again.";
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return RedirectToAction("CreateProject");
        }
        public ActionResult ManageProject()
        {
            if (Session["idUser"] == null)
            {
                return RedirectToAction("../Home/Login");
            }

            MyCommunity_DBEntities db = getDB();

            try
            {
                var projectList = (from project in db.Projects
                                   join user in db.Users on project.issuedBy equals user.id
                                   select project).ToList();

                var issuedByList = (from user in db.Users
                                    join project in db.Projects on user.id equals project.issuedBy
                                    select user).ToList();
                ViewData["projectList"] = projectList;
                ViewData["issuedByList"] = issuedByList;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return View();
        }
        public ActionResult UpdateProjects(FormCollection fc)
        {
            MyCommunity_DBEntities db = getDB();

            try
            {
                int projectID = Convert.ToInt16(fc["projectID"]);

                var projects = (from project in db.Projects
                                where project.id == projectID
                                select project);

                foreach (Project project in projects)
                {
                    project.name = fc["name"];
                    project.description = fc["description"];
                    project.cost = Convert.ToDecimal(fc["cost"]);
                    project.status = fc["status"];
                    project.dateStarted = Convert.ToDateTime(fc["dateStarted"]);
                    project.dateFinished = Convert.ToDateTime(fc["dateFinished"]);
                }
                int res = db.SaveChanges();
                if (res > 0)
                    Session["Message"] = "A project has been updated successfully.";
                else
                    Session["Message"] = "Failed to update project, please try again.";
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return RedirectToAction("ManageProject");
        }
        public ActionResult DeleteProjects()
        {
            MyCommunity_DBEntities db = getDB();

            try
            {
                int projectID = Convert.ToInt16(Request["projectID"]);
                var deleteProject = (from project in db.Projects
                                     where project.id == projectID
                                     select project).FirstOrDefault();

                db.Projects.Remove(deleteProject);
                int res = db.SaveChanges();
                if (res > 0)
                    Session["Message"] = "A project has been deleted successfully.";
                else
                    Session["Message"] = "Failed to delete project, please try again.";
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return RedirectToAction("ManageProject");
        }
    }
}

OOP_Community/Controllers/ResidentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OOP_Community.Models;

namespace OOP_Community.Controllers
{
    public class ResidentController : DBController
    {
        public ActionResult CreateResident()
        {
            if (Session["idUser"] == null)
            {
                return RedirectToAction("../Home/Login");
            }
            return View();
        }
        public ActionResult AddingResidents(FormCollection fc)
        {
            MyCommunity_DBEntities db = getDB();
            Resident r = new Resident();
            Address a = new Address();

            try
            {
                r.fname = fc["fname"];
                r.lname = fc["lname"];
                r.contactNo = fc["contactNo"];
                r.email = fc["email"];
                r.dateofBirth = Convert.ToDateTime(fc["dateofBirth"]);
                r.gender = fc["gender"];
                r.dateJoined = Convert.ToDateTime(fc["dateJoined"]);
                db.Residents.Add(r);
                var residentID = r.id;

                a.resident = residentID;
                a.block = fc["block"];
                a.lot = fc["lot"];
                a.street = fc["street"];
                a.subdivision = fc["subdivision"];
                db.Addresses.Add(a);

                int res = db.SaveChanges();
                if (res > 0)
                    Session["Message"] = "A resident has been created successfully.";
                else
                    Session["Message"] = "Failed to create resident, please try agan.";

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return RedirectToAction("CreateResident");
        }
        public ActionResult ManageResident()
        {
            if (Session["idUser"] == null)
            {
                return RedirectToAction("../Home/Login");
            }

            MyCommunity_DBEntities db = getDB();

            try
            {
                var residentList = (from resident in db.Residents
                                    join address in db.Addresses on resident.id equals address.resident
                                    select resident).ToList();

                var addressList = (from address in db.Addresses
                                   join resident in db.Residents on address.resident equals resident.id
                                   select address).ToList();

                ViewData["residentList"] = residentList;
                ViewData["addressList"] = addressList;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return View();
        }
        public ActionResult UpdateResidents(FormCollection fc)
        {
            MyCommunity_DBEntities db = getDB();

            try
            {
                int residentID = Convert.ToInt16(fc["residentID"]);

                var residents = (from resident in db.Residents
                                 where resident.id == residentID
                                 select resident);

                var addresses = (from address in db.Addresses
                                 where address.resident == residentID
                                 select address);

                foreach (Resident resident in residents)
                {
                    resident.fname = fc["fname"];
                    resident.lname = fc["lname"];
                    resident.gender = fc["gender"];
                    resident.dateofBirth = Convert.ToDateTime(fc["dateofBirth"]);
                    resident.email = fc["email"];
                    resident.contactNo = fc["contactNo"];
                    resident.dateJoined = Convert.ToDateTime(fc["dateJoined"]);
                }

                foreach (Address address in addresses)
                {
                    address.lot = fc["lot"];
                    address.block = fc["block"];
                    address.street = fc["street"];
                    address.subdivision = fc["subdivision"];
                }

                int res = db.SaveChanges();
                if (res > 0)
                    Session["Message"] = "Resident Information has been updated successfully.";
                else
                    Session["Message"] = "Failed to update resident information, please try again.";
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return RedirectToAction("ManageResident");
        }
        public ActionResult DeleteResidents()
        {
            MyCommunity_DBEntities db = getDB();

            try
            {
                int residentID = Convert.ToInt16(Request["residentID"]);
                var deleteResident = (from resident in db.Residents
                                      where resident.id == residentID
                                      select resident).FirstOrDefault();

                db.Residents.Remove(deleteResident);
                int res = db.SaveChanges();
                if (res > 0)
                    Session["Message"] = "Resident Information has been deleted successfully.";
                else
                    Session["Message"] = "Failed to delete resident information, please try again.";
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return RedirectToAction("ManageResident");
        }

    }
}

OOP_Community/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Community</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Fav Icon -->
    <link rel="apple-touch-icon" sizes="180x180" href="../Assets/img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../Assets/img/favicon-32x32.png">
    <link rel="manifest" href="../assets/img/site.webmanifest">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="../Assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="../Assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="../Assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="../Assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="../Assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="../Assets/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Modal Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</head>
<body>

    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="@Url.Action("Index","Home")" class="logo d-flex align-items-center">
                <img src="../Assets/img/logo.png" alt="">
                <span class="d-none d-lg-block">My Community</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div>

        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="../Assets/img/user.png" alt="Profile" class="rounded-circle">
                        <span class="d-none d-md-block dropdown-toggle ps-2">@Session["FullName"]</span>
                    </a>

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6>@Session["FullName"]</h6>
                            <span>@Session["Email"]</span>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a href="@Url.Action("Settings","Home")" class="dropdown-item d-flex align-items-center">
                                <i class="bi bi-gear"></i>
                                <span>Settings</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a href="@Url.Action("Logout","Home")" class="dropdown-item d-flex align-items-center">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Log Out</span>
                            </a>
                        </li>

                    </ul>
                </li>

            </ul>
        </nav>

    </header>

    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a href="@Url.Action("Index","Home")" class="nav-link collapsed">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li>


            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#resident-nav" data-bs-toggle="collapse">
                    <i class="bi bi-people"></i><span>Resident</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="resident-nav" class="nav-content collapse" data-bs-parent="#sidebar-nav">
                    <li>
                        <span>@Html.ActionLink("Create Resident", "CreateResident", "Resident")</span>
                    </li>
                    <li>
                        <span>@Html.ActionLink("Manage Resident", "ManageResident", "Resident")</span>
                    </li>
                </ul>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#due-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-cash-stack"></i><span>Monthly Dues</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="due-nav" class="nav-content collapse" data-bs-parent="#sidebar-nav">
                    <li>
                        <div>
                            <span>@Html.ActionLink("Create Monthly Dues", "CreateMonthlyDues", "MonthlyDues")</span>
                        </div>
                    </li>
                    <li>
                        <div>
                            <span>@Html.ActionLink("Manage Monthly Dues", "ManageMonthlyDues", "MonthlyDues")</span>
                        </div>
                    </li>
                </ul>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#project-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-clipboard"></i><span>Project</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="project-nav" class="nav-content collapse" data-bs-parent="#sidebar-nav">
                    <li>
                        <div>
                            <span>@Html.ActionLink("Create Project", "CreateProject", "Project")</span>
                        </div>
                    </li>
                    <li>
                        <div>
                            <span>@Html.ActionLink("Manage Project", "ManageProject", "Project")</span>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>

    </aside>

    <main id="main" class="main">
        @RenderBody()
    </main>

    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; @DateTime.Now.Year . <strong><span>My Community</span></strong>
        </div>
        <div class="credits">
            Created by <a href="">Van AJ Vanguardia</a>
        </div>
    </footer>

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)

    <script src="../Assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="../Assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="../Assets/vendor/chart.js/chart.min.js"></script>
    <script src="../Assets/vendor/echarts/echarts.min.js"></script>
    <script src="../Assets/vendor/quill/quill.min.js"></script>
    <script src="../Assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="../Assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="../Assets/vendor/php-email-form/validate.js"></script>

    <script src="../Assets/js/main.js"></script>
</body>
</html>